repos:
  - repo: local
    hooks:
      - id: update-brewfile
        name: Update Brewfile
        entry: /Users/jonathankumarich/.config/update_brewfile.sh
        language: script
        stages: [pre-commit]

